# In this example we are combining Register with Debug
---
  - hosts: all
    gather_facts: yes
    tasks: 
      - name: Get uptime
        shell: /usr/bin/uptime
        register: result
      - name: Print results
        debug:
          var: result.rc
# We can also use “var” submodule here instead of “msg”