# In this example we are using std.out & stdout.lines for parsing.
---
  - hosts:
    gather_facts: yes
    tasks: 
      - name: Get uptime
        shell: /usr/bin/uptime
        register: result
      - name: Print results
        debug:
          msg: "{{ result.stdout }}"  
# We can also use “msg” submodule here along with stdout or stdout_lines.