# Here we are going declare variables inside playbook using module "vars" (Array method)
---
  - hosts:
    gather_facts: no
    vars:
      package:
       - httpd
       - ntp
      service:
       - httpd
       - ntpd
    tasks:
      - name: Install packages
        yum:
         name: "{{ package[1] }}"
         state: present
      - name: restart services
        service:
          name: "{{ service[1] }}"
          state: restarted
   
  

