# In this example we are going pass this variables from command line using Extra_vars
---
  - hosts: all
    gather_facts: no
    tasks: 
      - name: Install {{ package }}
        yum: name={{ package }}  state=present
      - name: Enable {{ service }}
        service: name={{ service }} enabled=yes
      - name: Start {{ service }}
        service: name={{ service }} state=started

