---
  - hosts:
    remote_users: apache
    become: true
    gather_facts: no
    tasks:
        - name: Install apache
          yum: name=httpd state=present
          ignore_errors: true
          notify: restart apache
    handlers:
        - name: restart apache
          service: name=httpd state=restarted