# Playbook using with_items condition
---
  - hosts: all
    gather_facts: no
    tasks:
      - name: Install packages
        dnf: name={{ item }} state=present
        with_items:
         - httpd
         - ntp
   
   

