# Playbook using loops to create multiple user
---
  - hosts: dev
    gather_facts: no
    tasks:
      - name: add several users through loop
        user:
          name: "{{ item }}"
          state: present
          #groups: "wheel"
        loop:
          - testuser1
          - testuser2
     
   
   
   

