# Playbook using loops to create multiple users/groups
---
  - hosts: dev
    gather_facts: no
    tasks:
      - name: add several users through loop
        user:
          name: "{{ item.name }}"
          state: present
          groups: "{{ item.groups }}"
        loop:
          - { name: 'testuser1', groups: 'wheel' }
          - { name: 'testuser2', groups: 'wheel' }

     
   
   
   

