---
  - hosts:
    gather_facts: no
    tasks:
        - name: Insert new line into a file
          lineinfile:
            path: /etc/hosts
            line: 172.22.84.10 myhost.example.com myhost
          