---
  - hosts: all
    gather_facts: no
    tasks:
        - name: Insert new line into a file before specific line
          lineinfile:
            path: /etc/hosts
            insertbefore: '^127.0.0.1'
            line: 13.233.152.46 myhost.example.com myhost
          